name: py38cmp-core

channels:
- conda-forge
- aramislab
- mrtrix3

dependencies:
- python=3.8
- pip=20.1.1
- ants=2.2.0
- numpy=1.21.0
- matplotlib=3.2.2
- graphviz=2.40.1
- traits=6.2.0
- traitsui=7.0.0
- configparser=5.0.0
- nipype=1.8.0
- git-annex=8.20200617
- pydotplus=2.0.2
- dipy=1.3.0
- cvxpy-base=1.3.1
- cvxpy=1.3.1
- obspy=1.2.2
- mrtrix3=3.0.2

- pip:
    - coverage==5.2.1
    - duecredit==0.8.0
    - mne==0.24.1
    - mne_connectivity==0.3
    - datalad[full]==0.17.2
    - datalad-container==1.1.6
    - datalad-neuroimaging==0.3.1
    - pybids==0.14.0
    - statsmodels==0.11.1
    - networkx==2.6.3
    - pydicom==2.2.2
    - pycartool==0.1.1
    - pandas==1.4.0
    - nibabel==3.2.2
    - scipy==1.5.4

