name: py37cmp-eeg

channels:
  - conda-forge
  - aramislab
  - mrtrix3
  - anaconda

dependencies:
  - python=3.7
  - pip=21.3.1
  - datalad=0.17.2
  - jupyterlab=3.2.8
  - numpy=1.21.5
  - matplotlib=3.5.1
  - traits=6.3.2
  - graphviz=2.50.0
  - configparser=5.2.0
  - nipype=1.7.0
  - dipy=1.3.0
  - pyside2=5.13.2
  - indexed_gzip=1.6.4
  - conda-forge::mne=0.24.1

  - pip:
      - duecredit==0.9.1
      - future==0.18.2
      - nibabel==3.2.2
      - pybids==0.14.0
      - networkx==2.6.3
      - pycartool==0.1.1
      - mne-connectivity==0.2
      - connectomemapper==3.1.0
