name: cmp3-tutorial
channels:
  - conda-forge
  - desilinguist
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - datalad=0.17.2
  - jupyterlab=3.2.8
  - matplotlib=3.5.1
  - networkx=2.5
  - nibabel=3.2.1
  - nilearn=0.8.1
  - numpy=1.21.5
  - pip=21.3.1
  - scipy=1.7.3
  - seaborn=0.11.0
  - pip:
    - nibabel==3.2.2
    - pandas==1.3.5
    - pybids==0.14.0
    - pygsp==0.5.1
    - connectomemapper==3.0.3
